# Generated by Django 4.2.1 on 2023-05-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_dilla_emp_salary_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportcustomer',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customerprofile'),
        ),
    ]
