# Generated by Django 4.2.1 on 2023-05-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_staffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='level',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='phone_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='sex',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
        ),
    ]
