# Generated by Django 4.2.1 on 2023-05-22 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_staffprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile1', to='app.staff'),
        ),
    ]
