# Generated by Django 4.2.1 on 2023-05-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_loanrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='customer',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customerprofile'),
        ),
    ]
