# Generated by Django 4.2.1 on 2023-05-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_loanrequest_customer_loanrequest_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
    ]
