# Generated by Django 4.2.1 on 2023-06-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_loanrequesthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='loan_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='LoanRequestHistory',
        ),
    ]
