# Generated by Django 4.2.1 on 2023-06-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_loanrequest_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balanceadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
