# Generated by Django 4.2.1 on 2023-06-14 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_balanceadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balanceadmin',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.admin'),
        ),
    ]
