# Generated by Django 4.2.1 on 2023-06-14 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_balanceadmin_adminprofile_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='balance',
            new_name='balance1',
        ),
    ]
