# Generated by Django 4.2.1 on 2023-06-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_customerprofile_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
