# Generated by Django 4.2.1 on 2023-06-16 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_financeprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complaincustomer',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='app.customerprofile'),
        ),
    ]
