# Generated by Django 4.2.1 on 2023-10-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_custbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custbalance',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='custbalance',
            name='count',
        ),
    ]
