# Generated by Django 4.2.1 on 2023-10-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_custbalance_balance_remove_custbalance_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='custbalance',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customerprofile'),
        ),
    ]
