# Generated by Django 4.2.1 on 2023-06-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_salary_custbalance_salary_10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custbalance',
            name='salary_10',
            field=models.IntegerField(default=0),
        ),
    ]
