# Generated by Django 4.2.1 on 2023-06-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_custbalance_salary_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='custbalance',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
