# Generated by Django 4.2.1 on 2023-07-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_custbalance_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phone_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='salary_p',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='sex',
            field=models.CharField(default='', max_length=100),
        ),
    ]
