# Generated by Django 4.2.1 on 2023-07-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_customerprofile_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='willing',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
