# Generated by Django 4.2.1 on 2023-08-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_customerprofile_willing'),
    ]

    operations = [
        migrations.AddField(
            model_name='custbalance',
            name='willing',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
