# Generated by Django 4.2.1 on 2023-08-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_custbalance_willing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='willing',
        ),
    ]
