# Generated by Django 4.2.1 on 2023-08-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_customerprofile_willing'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='willing_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
