# Generated by Django 4.2.1 on 2023-08-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='dilla_emp',
            name='account_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
