# Generated by Django 4.2.1 on 2023-08-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_dilla_emp_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='customer_id',
            new_name='user',
        ),
    ]
