# Generated by Django 4.2.1 on 2023-09-01 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customerprofile'),
        ),
    ]
