# Generated by Django 4.2.1 on 2023-09-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_account_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_pass',
            field=models.CharField(default='', max_length=100),
        ),
    ]
