# Generated by Django 4.2.1 on 2023-07-03 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_account_account_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customerprofile')),
            ],
        ),
    ]
