# Generated by Django 4.2.1 on 2023-07-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_loanrequest1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanRequest1',
        ),
    ]
