# Generated by Django 4.2.1 on 2023-08-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_delete_loanrequest1'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cust_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
