# Generated by Django 4.2.1 on 2023-08-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_loanrequest_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportcustomer',
            name='cus_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
